version: '3.8'

services:
  scout-clone:
    build: .
    container_name: scout-ai-clone
    ports:
      - "3000:80"
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scout-network

networks:
  scout-network:
    driver: bridge